export const SUBMIT_GENERAL_PROFILE = 'SUBMIT_GENERAL_PROFILE';
export const GET_KEYWORDS = 'GET_KEYWORDS';
export const SUBMIT_EXPERTISE_PROFILE = 'SUBMIT_EXPERTISE_PROFILE';
export const SUBMIT_INVESTOR_STATEMENT_PROFILE = 'SUBMIT_INVESTOR_STATEMENT_PROFILE';