export const INVEST_STARTUP = 'INVEST_STARTUP';
export const GET_INVEST_MATCHES = 'GET_INVEST_MATCHES';
export const GET_SELECTED_INVEST_MATCH = 'GET_SELECTED_INVEST_MATCH';
export const SUBMIT_STARTUP_QUESTION = 'SUBMIT_STARTUP_QUESTION';
export const GET_PROSPECT_MATCHES = 'GET_PROSPECT_MATCHES';
export const TOGGLE_PROSPECT_SWITCH = 'TOGGLE_PROSPECT_SWITCH';