export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const DISABLE_LOADER = 'DISABLE_LOADER';
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const SWITCH_MODAL = 'SWITCH_MODAL';
export const DATA_PROVIDERS_INITIALIZED = 'DATA_PROVIDERS_INITIALIZED';