export const GET_PORTFOLIO = 'GET_PORTFOLIO';
export const GET_PORTFOLIO_UPDATE_LOGS = 'GET_PORTFOLIO_UPDATE_LOGS';
export const ACTIVE_SECTIONS_UPDATE = 'ACTIVE_SECTIONS_UPDATE';
export const GET_COMPANY_NEWSFEED = 'GET_COMPANY_NEWSFEED';
export const EXPAND_COMPANY_NEWSFEED = 'EXPAND_COMPANY_NEWSFEED';
